project:
  type: website

website:
  site-url: https://stat210a.berkeley.edu/fall-2025/
  google-analytics: G-B8G2041HSB
  sidebar:
    style: docked
    title: "Stat 210a"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat210a/fall-2025
    contents:
      - href: index.qmd
        text: Home / Schedule
      - section: "Course Logistics"
        contents:
          - faq.qmd
          - syllabus.qmd
          - calendar.qmd
      - handwritten-notes.qmd
      - section: "Course Reader"
        contents:
          - reader/introduction.qmd
          - reader/probability.qmd
      - href: license.qmd
        text: License


format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html
